### ISSUE TITLE
Measurements are grouped by testserver

### ISSUE THREAD

**Issue by Tidle999** [masterwishx/Speedtest-Tracker-v2-InfluxDBv2#1]
seems that the measurements are grouped by testservers, that results in unexpected dashboards with multiple lines and entries;

![image](https://user-images.githubusercontent.com/36228711/224021894-6c28d803-850e-44d6-9bc1-f43b43b3fcee.png)
![image](https://user-images.githubusercontent.com/36228711/224021964-3927c71b-ee28-4209-84c5-ffa227a87a0d.png)

any idea how to fix this?

**Comment by Tidle999** [comment]
answered by myself,

  |> group(columns: ["_field"])

has to be added to the query for the columns that should not be grouped by server

for example:

from(bucket: "speedtestracker")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "speedtest")
  |> filter(fn: (r) => r["_field"] == "download_bits" or r["_field"] == "upload_bits")
  |> group(columns: ["_field"])
  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)
  |> yield(name: "last")

**Comment by masterwishx** [comment]
Thanks, im using only one server ,so i didn't saw this problem...

**Comment by Tidle999** [comment]
Isn’t it automatically using different test server for the speed tests? I did Not configure anything special regarding this.

**Comment by masterwishx** [comment]
you can add it by yourself if you want specific server

**Comment by masterwishx** [comment]
Use Merge in Transform to fix it , i will update it later

**Comment by masterwishx** [comment]
also can be used:
|> drop(columns: ["server_host","server_name"])
