### ISSUE TITLE
Show Value 0 when no data?

### ISSUE THREAD

**Issue by Ja50n-Kru** [masterwishx/Speedtest-Tracker-v2-InfluxDBv2#2]
I'm having issues with my internet connection, and there are times (sometimes for a few hours) that speedtesttracker cannot run and fails. Is there any way to show 0 values on the download graph, for example, when there is no data? At the moment the data from the last point is joined to the next point. 
![ShowZero](https://github.com/masterwishx/Speedtest-Tracker-v2-InfluxDBv2/assets/66164653/19933904-c321-4d4c-96c0-539090500853)

**Comment by masterwishx** [comment]
sure :  

![image](https://github.com/masterwishx/Speedtest-Tracker-v2-InfluxDBv2/assets/28630321/31607ef5-e5ad-40e8-a1fc-0908632b1c6d)


Also check newer container : https://github.com/alexjustesen/speedtest-tracker

**Comment by Ja50n-Kru** [comment]
Perfect, thanks! Much appreciate your efforts on this!
