### ISSUE TITLE
FEATURE REQUEST: Modify for two or more connections

### ISSUE THREAD

**Issue by burnbrighter** [masterwishx/Speedtest-Tracker-v2-InfluxDBv2#4]
Hoping there is a way to add a second internet connection.   My use case is to compare my VPN speeds with my open internet speeds.  I actually have two VPN connection and  want to find a way to overlay 3 different connections.  But I think I can reverse engineer two connections shown.  I have each going to different buckets in influxdb2.  Any hints are appreciated.

**Comment by masterwishx** [comment]
> Hoping there is a way to add a second internet connection

Sure, you can try to add more query from other bucket in same panel or duplicate panel if you want every bucket in other panel.
Or you can add variable in dashboard setting for bucket , and view all data by this variable , you will have like now but can change bucket var to see info of other bucket.

**Comment by masterwishx** [comment]
here example how to use variable: 

![image](https://github.com/masterwishx/Speedtest-Tracker-v2-InfluxDBv2/assets/28630321/ea5ef292-4bb6-4e71-9465-f69fccf5e20c)

**Comment by masterwishx** [comment]
Please check new file

**Comment by burnbrighter** [comment]
This is working really well, thank you!  Is there a way to **simultaneously** show two different connections in the same graph with different graph colors?  Use case:  I have a standard connection (open internet) and connection traversing my VPN.  I want to see both of those connections and their metrics in the same graphs for comparison purposes.

**Comment by masterwishx** [comment]
> This is working really well, thank you! Is there a way to **simultaneously** show two different connections in the same graph with different graph colors? Use case: I have a standard connection (open internet) and connection traversing my VPN. I want to see both of those connections and their metrics in the same graphs for comparison purposes.

i think you can make it by : read values from two buckets in one panel but it needs more influxdbv2 commands ,maybe you can find examples in google
