### ISSUE TITLE
Improvement suggestion

### ISSUE THREAD

**Issue by skyeci-draytek** [masterwishx/Speedtest-Tracker-v2-InfluxDBv2#5]
Hi. 

Love the dashboard, thanks. I'm fairly new to grafana. Setup it all up for influx dbv2 but I was getting no data in the dashboard... finally after renaming my bucket to "speedtest-tracker-new" it worked. I think it would be very helpful in the guide for v2 to mention to rename or create a bucket as mentioned above. 

You also have a broken link in the grafana dashboard page here.https://grafana.com/grafana/dashboards/17808-speedtest-tracker-v2-influxdbv2/ 
The first mentioned link is broken.

Thanks again for a great dash board.

**Comment by masterwishx** [comment]
> The first mentioned link is broken.

Thanks for feedback ,link is fixed .

i will post tutorial , please check it ...
