### ISSUE TITLE
Formatting?

### ISSUE THREAD

**Issue by skyeci-draytek** [masterwishx/Speedtest-Tracker-v2-InfluxDBv2#6]
Not so much an issue but since the recent upgrade to spt the grafana interface has gained some extra columns.
Is this expected? 
Many Thanks for your dashboard.
![Screenshot_20240420_071825_Samsung Internet](https://github.com/masterwishx/Speedtest-Tracker-v2-InfluxDBv2/assets/81510309/0a2d1b54-02aa-413a-9676-8d2ce1e4a508)

**Comment by masterwishx** [comment]
> Not so much an issue but since the recent upgrade to spt the grafana interface has gained some extra columns. Is this expected? Many Thanks for your dashboard. 


Already fixed, will make pr today later, check for new file....

**Comment by skyeci-draytek** [comment]
Thanks so much. Perhaps you could post where I can download it when it's up.cheers

**Comment by masterwishx** [comment]
> Thanks so much. Perhaps you could post where I can download it when it's up.cheers

Updated , You can download file from here or from garafana

**Comment by skyeci-draytek** [comment]
Works great thanks. One quick question. Is it possible to change the default view to the past 24 hours when the dashboard opens? Is this easy to set to default somewhere?

Thanks again

**Comment by masterwishx** [comment]
> Works great thanks. One quick question. Is it possible to change the default view to the past 24 hours when the dashboard opens? Is this easy to set to default somewhere?

Sure ,Go to where (last 3 hours) change to Last 24 hours, then save dashboard

![image](https://github.com/masterwishx/Speedtest-Tracker-v2-InfluxDBv2/assets/28630321/362f04e8-6730-41a6-8b6e-85fdbb7008e3)

**Comment by skyeci-draytek** [comment]
Thank you 😊
