### ISSUE TITLE
No data being displayed on dash 17808

### ISSUE THREAD

**Issue by Skyeci73** [masterwishx/Speedtest-Tracker-v2-InfluxDBv2#7]
Hi. 

Had to rebuild my pc that I use for displaying grafana and spt etc.
Everything now installed but I'm unable to get any data being displayed in grafana using dash 17808. 
I have checked the influx bucket which shows active data (bucket called speedtest-tracker-new)
Dashboard panels just report no data..

I'm at a loss so any help appreciated in trying to resolve it. I am using the latest config for STT
Thanks

**Comment by masterwishx** [comment]
> Hi.
> 
> Had to rebuild my pc that I use for displaying grafana and spt etc. Everything now installed but I'm unable to get any data being displayed in grafana using dash 17808. I have checked the influx bucket which shows active data (bucket called speedtest-tracker-new) Dashboard panels just report no data..
> 
> I'm at a loss so any help appreciated in trying to resolve it. I am using the latest config for STT Thanks

You can set any bucket name now, it support multi bucket.
If you have no data check if you set right token for influxdb2 in data source.
Than can read data from bucket.
Also check grafana logs

**Comment by Skyeci73** [comment]
Thanks. Somehow it's working again so all good. Started again. Maybe I messed something up late last night..
Thanks for the dashboard
