### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by skyeci-draytek** [masterwishx/Speedtest-Tracker-v2-InfluxDBv2#8]
Hi. Thanks for your dashboard. 
Just wondered if its possible to have a feature added such as at the top of the dashboard just above the first panel

"Last data recieved at" : time recieved.

Cheers

**Comment by masterwishx** [comment]
Do you mean add time when last data received?
Can you explain more?

**Comment by skyeci-draytek** [comment]
Hi there.

something a bit like this perhaps, sorry had to improvise in paint :)
just a small panel at the top that shows the current time and then the last time a test or data recieved. :)
![image](https://github.com/user-attachments/assets/0e8890e8-69f2-48b0-b1d8-32efe5b1fd40)

thanks

**Comment by masterwishx** [comment]
I will think but not shure how best to add it.
You can add time clock panel for yourself already.

**Comment by cypherstream** [comment]
At the very bottom of the dashboard is an All tests table sorted by most recent.

**Comment by masterwishx** [comment]
> At the very bottom of the dashboard is an All tests table sorted by most recent.

Yep, but he wanted like separate panel with time.
We have already latest test result in upper status panels also we can see time in download panel.

**Comment by masterwishx** [comment]
> Hi there.
> 
> something a bit like this perhaps, sorry had to improvise in paint :) just a small panel at the top that shows the current time and then the last time a test or data recieved. :)
> 
> thanks

is it looks OK ?

![image](https://github.com/user-attachments/assets/cf5af9cf-206e-46b5-8081-c896fe20b5c9)

**Comment by skyeci-draytek** [comment]
Hi. I think that looks good.

Are you aware of the new update to SPT with regards to influx... will it have implications to your dashboard etc? I haven't updated yet as I didn't want to break my dashboard.

Thanks

**Comment by masterwishx** [comment]
> Hi. I think that looks good.
> 
> Are you aware of the new update to SPT with regards to influx... will it have implications to your dashboard etc? I haven't updated yet as I didn't want to break my dashboard.
> 
> Thanks

I saw they working to fix influxdbv2 errors, I have auto update for containers. Not checked yet if all working fine but will check and will upload here and to grafana if they released update

**Comment by masterwishx** [comment]
> Are you aware of the new update to SPT with regards to influx... will it have implications to your dashboard etc? I haven't updated yet as I didn't want to break my dashboard.

dont update yet its broken for now

**Comment by skyeci-draytek** [comment]
Ok thanks. Hopefully you can pass on what's required to make it work

Thanks so much

**Comment by masterwishx** [comment]
> Ok thanks. Hopefully you can pass on what's required to make it work
> 
> Thanks so much

the update broke influxdb bucket for me :(

**Comment by masterwishx** [comment]
waiting for fix ...

**Comment by masterwishx** [comment]
> Ok thanks. Hopefully you can pass on what's required to make it work
> 
> Thanks so much

Sorry the app working fine but it broke the grafana dashboard, so I fixed some stuff now trying to get some variables to work as they moved them from fields to tags...

**Comment by masterwishx** [comment]
Updated dashboard to be compatible with new version will post today later...

**Comment by Skyeci73** [comment]
Great. Thanks very much. Will it have the same dashboard ID number or different. Any changes needed in influx?

**Comment by masterwishx** [comment]
> Great. Thanks very much. Will it have the same dashboard ID number or different. Any changes needed in influx?

same ID , no changes needs in influxdb ...

**Comment by cypherstream** [comment]
Yikes I have a lot of various dashboards connected to influx for various things.  Thanks for the heads up.

**Comment by Skyeci73** [comment]
Thanks. It's working for me as well. Now I have seen the additional box properly is it possible to display the time stamp of the last test in the box  rather than "a few seconds ago"?

Thanks so much

**Comment by masterwishx** [comment]
> Thanks. It's working for me as well. Now I have seen the additional box properly is it possible to display the time stamp of the last test in the box rather than "a few seconds ago"?
> 
> Thanks so much

I made it to be same as in public dashboard of speedtest tracker but you can change it.
Go to standard options->unit change to time how you want it to look

**Comment by masterwishx** [comment]
Also found it show wrong value sometimes so trying to fix...

**Comment by Skyeci73** [comment]
Great thanks. I'm playing with an 8gb/8gb symmetrical service. Downloads are recorded correctly at 8gb but the cli can't seem to cope with catching the upload...🤔😂
![Screenshot_20241209_045235_Samsung Internet](https://github.com/user-attachments/assets/d0217a5a-bb3d-4642-8395-c0d8fdae5072)

**Comment by masterwishx** [comment]
I have no problem with it but will check it.
Are you have other speed in speedtest-tracker?
